# yaml-language: cloudbuild
# Type: Google Cloud Build Configuration
# Description: Build and push Docker image to Container Registry
# Author: ML
# Version: 1.0
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/gcpdevops'
      - '.'
images:
  - 'gcr.io/$PROJECT_ID/gcpdevops'

options:
  logging: CLOUD_LOGGING_ONLY
