# yaml-language: cloudbuild
# Type: Google Cloud Build Configuration
# Description: Build and push Docker image to Container Registry
# Author: ML
# Version: 1.0
steps:
# Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/gcpdevops'
    - '.'
# Push Docker image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'gcr.io/$PROJECT_ID/gcpdevops'
# Deploy container to GKE
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
    - run
    - '--filename=gke.yaml'
    - '--image=gcr.io/$PROJECT_ID/gcpdevops'
    - '--cluster=gcp-devps-project'
    - '--location=us-central1-c'  
    - '--namespace=gcp-devops-prod'   
    
options:
  logging: CLOUD_LOGGING_ONLY
